### ISSUE TITLE
conda env?

### ISSUE THREAD

**Issue by cdeil** [adbreind/open-standard-models-2019#1]
Thanks for sharing this on Github!!!

Would it be possible to add a conda env file, and/or pip requirements file?

This would allow one to easily get an execution environment to try out the notebooks locally.

I also see a "binder" folder, but no mention of binder in the readme. Is is working? If yes, maybe you could add "launch in binder" link to the README?

**Comment by adbreind** [comment]
Thanks! I did add a binder link and it does work :) ... Feel free to try that out!

**Comment by cdeil** [comment]
🎉
